<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"场地类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChangdi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"场地维护类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChangdiWeihu"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"课程类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"器材类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQicai"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"器材维护类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQicaiWeihu"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"优惠信息类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYouhuixinxi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"健身资讯类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZixun"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报表",
                            "删除"
                        ],
                        "menu":"教练管理",
                        "menuJump":"列表",
                        "tableName":"jiaolian"
                    }
                ],
                "menu":"教练管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程收藏管理",
                        "menuJump":"列表",
                        "tableName":"kechengCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程预约管理",
                        "menuJump":"列表",
                        "tableName":"kechengOrder"
                    }
                ],
                "menu":"课程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"器材管理",
                        "menuJump":"列表",
                        "tableName":"qicai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"器材收藏管理",
                        "menuJump":"列表",
                        "tableName":"qicaiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"器材租赁管理",
                        "menuJump":"列表",
                        "tableName":"qicaiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"器材维护管理",
                        "menuJump":"列表",
                        "tableName":"qicaiWeihu"
                    }
                ],
                "menu":"器材管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"场地管理",
                        "menuJump":"列表",
                        "tableName":"changdi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"场地收藏管理",
                        "menuJump":"列表",
                        "tableName":"changdiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"场地预约管理",
                        "menuJump":"列表",
                        "tableName":"changdiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"场地维护管理",
                        "menuJump":"列表",
                        "tableName":"changdiWeihu"
                    }
                ],
                "menu":"场地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"优惠信息管理",
                        "menuJump":"列表",
                        "tableName":"youhuixinxi"
                    }
                ],
                "menu":"优惠信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"健身资讯管理",
                        "menuJump":"列表",
                        "tableName":"zixun"
                    }
                ],
                "menu":"健身资讯管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"会员管理",
                        "menuJump":"列表",
                        "tableName":"huiyuan"
                    }
                ],
                "menu":"会员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报表",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"员工管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"教练管理",
                        "menuJump":"列表",
                        "tableName":"jiaolian"
                    }
                ],
                "menu":"教练管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程收藏管理",
                        "menuJump":"列表",
                        "tableName":"kechengCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课程预约管理",
                        "menuJump":"列表",
                        "tableName":"kechengOrder"
                    }
                ],
                "menu":"课程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"器材管理",
                        "menuJump":"列表",
                        "tableName":"qicai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"器材收藏管理",
                        "menuJump":"列表",
                        "tableName":"qicaiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"器材租赁管理",
                        "menuJump":"列表",
                        "tableName":"qicaiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"器材维护管理",
                        "menuJump":"列表",
                        "tableName":"qicaiWeihu"
                    }
                ],
                "menu":"器材管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"场地管理",
                        "menuJump":"列表",
                        "tableName":"changdi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"场地收藏管理",
                        "menuJump":"列表",
                        "tableName":"changdiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"场地预约管理",
                        "menuJump":"列表",
                        "tableName":"changdiOrder"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"场地维护管理",
                        "menuJump":"列表",
                        "tableName":"changdiWeihu"
                    }
                ],
                "menu":"场地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"优惠信息管理",
                        "menuJump":"列表",
                        "tableName":"youhuixinxi"
                    }
                ],
                "menu":"优惠信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"健身资讯管理",
                        "menuJump":"列表",
                        "tableName":"zixun"
                    }
                ],
                "menu":"健身资讯管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"员工",
        "tableName":"yuangong"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"教练管理",
                        "menuJump":"列表",
                        "tableName":"jiaolian"
                    }
                ],
                "menu":"教练管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"课程收藏管理",
                        "menuJump":"列表",
                        "tableName":"kechengCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"课程预约管理",
                        "menuJump":"列表",
                        "tableName":"kechengOrder"
                    }
                ],
                "menu":"课程管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"器材收藏管理",
                        "menuJump":"列表",
                        "tableName":"qicaiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"器材租赁管理",
                        "menuJump":"列表",
                        "tableName":"qicaiOrder"
                    }
                ],
                "menu":"器材管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"场地收藏管理",
                        "menuJump":"列表",
                        "tableName":"changdiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"场地预约管理",
                        "menuJump":"列表",
                        "tableName":"changdiOrder"
                    }
                ],
                "menu":"场地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"优惠信息管理",
                        "menuJump":"列表",
                        "tableName":"youhuixinxi"
                    }
                ],
                "menu":"优惠信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"健身资讯管理",
                        "menuJump":"列表",
                        "tableName":"zixun"
                    }
                ],
                "menu":"健身资讯管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"会员",
        "tableName":"huiyuan"
    }
];

var hasMessage = '';
